64 livechat and chat managers updates update
Project-Stage-Academy/UA-1131_Forum-PS pull request #73
Opened 2024-03-12 18:32 UTC by haodn98

2024-03-12 19:44 UTC, parsival2022 approved these changes

2024-03-13 16:01 UTC, mehalyna requested changes

2024-03-13 16:01 UTC, mehalyna commented on livechats/managers.py
> +        conversation_list = conversation_list.reverse()
The `list.reverse()` method reverses the list in place and returns `None`. This line will set `conversation_list` to `None`, which is likely not the intended behavior.
You may use `conversation_list.reverse()` without assignment to reverse the list in place, or `conversation_list = conversation_list[::-1]` to create a reversed copy of the list

2024-03-13 16:01 UTC, mehalyna commented on livechats/managers.py
> +            for i in range(math.ceil(messages / 50)):
`messages` is a list, and you cannot divide a list by an integer, which will raise a `TypeError`.
Use `len(messages)` instead to get the number of messages: `range(math.ceil(len(messages) / 50))`

2024-03-13 16:01 UTC, mehalyna commented on livechats/managers.py
> +                    cls.db.update_one({"_id": ObjectId(conversation_id)}, {"$push": {"messages": messages[0:50]}})
When adding multiple messages, you should use the `$each` operator inside `$push` to append each message in the list to the messages array.
You can modify the update statement to use: `{"$push": {"messages": {"$each": messages[0:50]}}}`

2024-03-13 16:01 UTC, mehalyna commented on livechats/managers.py
> +                    messages = messages[50::]
The slicing syntax is slightly off. Use `messages = messages[50:]` to get the remaining messages after the first 50

2024-03-13 16:20 UTC, haodn98 commented on livechats/managers.py
> +        conversation_list = conversation_list.reverse()
fixed

2024-03-13 16:20 UTC, haodn98 commented on livechats/managers.py
> +            for i in range(math.ceil(messages / 50)):
fixed

2024-03-13 16:20 UTC, haodn98 commented on livechats/managers.py
> +                    cls.db.update_one({"_id": ObjectId(conversation_id)}, {"$push": {"messages": messages[0:50]}})
added, thanks

2024-03-13 16:21 UTC, haodn98 commented on livechats/managers.py
> +                    messages = messages[50::]
fixed

2024-03-13 18:08 UTC, mehalyna approved these changes

2024-03-13 18:27 UTC, ydmyterko approved these changes

2024-03-13 19:17 UTC, merged